### ISSUE TITLE
/me ignores

### ISSUE THREAD

**Issue by romangraef** [ed588/testing#1]
Amn't i awesome

**Comment by ed588** [comment]
No

**Comment by ed588** [comment]
This is comment number 1!

**Comment by ed588** [comment]
This is comment number 2!

**Comment by ed588** [comment]
This is comment number 3!

**Comment by ed588** [comment]
This is comment number 4!

**Comment by ed588** [comment]
This is comment number 5!

**Comment by ed588** [comment]
This is comment number 6!

**Comment by ed588** [comment]
This is comment number 7!

**Comment by ed588** [comment]
This is comment number 9!
